# Directories for input data
data:
  root_dir: "/net/scratch2/rachelgordon/zf_data_192_slices/zf_kspace"
  dataset_key: "kspace"
  split_file: "/home/rachelgordon/mri_recon/radial-breast-ddei/data/data_split.json"
  val_split_ratio: 0.2
  height: 320
  width: 320
  timeframes: 8
  total_spokes: 288
  samples: 640
  coils: 16
  eval_timeframes: 8
  eval_spokes: 36
  spf_aug: false
  weight_accelerations: false
  fpg: 36
  train_spokes_per_frame: 36
  slices: 192
  slices_to_eval: 1
  eval_frequency: 5
  flip_kspace: false
  traj_method: get_traj

# Experiment settings
experiment:
  output_dir: "/net/projects2/annawoodard/rachelgordon/experiments"
  cluster: "DSI"

# DataLoader settings
dataloader:
  batch_size: 1
  shuffle: true
  num_workers: 2
  max_subjects: 300
  num_random_slices: 1
  slice_idx: 41
  slice_range_start: None
  slice_range_end: None

# Model settings
model:
  name: "MambaRecon"
  encode_acceleration: false
  encode_time_index: false
  mamba:
    patch_size: 2
    in_chans: 2
    num_blocks: 6
    block_depth: 2
    hidden_dim: 128
    d_state: 16
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    patch_norm: true
    use_checkpoint: false
    checkpoint_use_reentrant: false
    dc_step: 1.0
  optimizer:
    name: "Adam"
    lr: 0.0005
    weight_decay: 0.0
    b1: 0.9
    b2: 0.999
    eps: 0.000000001
  losses:
    use_ei_loss: false
    mc_loss:
      weight: 10
      metric: "MAE"
    ei_loss:
      metric: "MSE"
      temporal_transform: "warp"
      spatial_transform: "all"
      rotate_range: 20
      weight: 0
      warmup: 25
      duration: 10000
      subsample_ratio_min: 0.7
      subsample_ratio_max: 0.95
      warp_ratio_min: 0.6
      warp_ratio_max: 0.95
      no_grad: false
  norm: "both"

# Training settings
training:
  epochs: 400
  save_interval: 1
  plot_interval: 20
  device: "cuda"
  multigpu: true
  edge_time_index_sampling: false
  curriculum_learning:
    enabled: false
    phases:
      - name: "Phase 1: Moderate Accelerations"
        start_epoch: 1
        train_spokes_range: [16, 24, 36]
        eval_spokes_per_frame: 16
        eval_num_frames: 18
      - name: "Phase 2: Higher Accelerations"
        start_epoch: 2
        train_spokes_range: [8, 16, 24, 36]
        eval_spokes_per_frame: 8
        eval_num_frames: 36
      - name: "Phase 3: Ultra-High Accelerations"
        start_epoch: 3
        train_spokes_range: [2, 4, 8, 16, 24, 36]
        eval_spokes_per_frame: 2
        eval_num_frames: 144

evaluation:
  num_samples: 15
  simulated_dataset_path: "/net/scratch2/rachelgordon/dro_dataset_frontpad"
  chunk_size: 36
  chunk_overlap: 18
  rescale: false
  val_noise_level: 0

debugging:
  calc_step_0: true
  calc_step_0_val: true
  enable_gradient_monitoring: true
  monitoring_interval: 5
